require("config.keymaps.general")
require("config.keymaps.test_navigation")
require("config.keymaps.multiple_cursors")
require("config.keymaps.magic_keys")
require("config.keymaps.colorschemes")
require("config.keymaps.formatting")
